config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'

  resources :cocktails, only: [:new, :create, :index, :show] do
    resources :doses, only: [:new, :create, :show]
  end
  resources :doses, only: [:destroy]
  get "cocktails/search", to: "cocktails#search", as: :search
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true, presence: true, allow_blank: false, uniqueness: {case_sensitive: false}
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates :description, presence: true, allow_blank: false
  validates_uniqueness_of :cocktail_id, scope: [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, uniqueness: true, presence: true, allow_blank: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    if params[:query]
      @cocktails = Cocktail.where(name: params[:query].downcase)
    else
      @cocktails = Cocktail.all
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new]

  def new
    @dose = Dose.new()
  end

  def create
    @dose = Dose.new(dose_params)

    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy

    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<div class="container text-center">
  <div class="form-group">
    <div class="test">
      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit "Validate", class: "btn btn-primary", id: "add-dose"%>
        <%= link_to '<i class="fas fa-undo-alt"></i> Back'.html_safe, cocktails_path, class: "btn btn-primary"%>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="trompette-banner">
  <h1>Nos cocktails</h1>
</div>


<div class="container" id="home-cocktails">
  <h2 class="text-center">Une envie particulière ?</h2>
  <div class="row">
    <% @cocktails.each do |cocktail|%>
      <div class="col-xs-12 col-sm-4">
        <div class="card">
           <% image_url = "https://source.unsplash.com/featured/300x300/?cocktail,#{cocktail.name}" %>
           <div class="card text-center">
            <img src= <%= image_url%> alt="Cocktail">
            <div class="card-category"></div>
            <div class="card-description">
              <h2><%= cocktail.name.capitalize %></h2>
            </div>
            <%= link_to "Recipe", cocktail_path(cocktail), class: "card-link" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="container text-center">
  <div class="row">
    <div class="col-xs-12" id="new_cocktail">
      <%= link_to '<i class="fas fa-plus"></i> Add a new cocktail'.html_safe, new_cocktail_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

<!-- <button id="sweet-alert-demo" class="btn btn-primary">Click me!</button> -->

app/views/cocktails/new.html.erb
<div class="container">
  <h1 class="text-center">New cocktail</h1>

  <%= render 'form'%>
</div>

app/views/cocktails/show.html.erb
<div class="container">
    <h2><%= @cocktail.name %></h2>
    <hr>
    <div class="ingredient-container">
      <table class="table">
        <thead>
          <tr>
              <th scope="col">#</th>
              <th scope="col">Ingrédients</th>
              <th scope="col">Descriptions</th>
              <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @cocktail.ingredients.each_with_index do |ingredient, index| %>
            <% ingredient.doses.each do |dose| %>
              <tr>
                <th scope="row"><%= index + 1 %></th>
                <td class="font-italic"><%= ingredient.name%></td>
                <td class="font-italic"> <%= dose.description%></td>
                <td><%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, dose_path(id: dose.id, cocktail_id: @cocktail.id),
                  method: :delete,
                  data: { confirm: "Are you sure?" }, class: "text-center" %></td>

              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <hr>
      <% if @cocktail.photo.present? %>
        <%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>
      <% end %>
    </div>
    <hr>
  <%= link_to '<i class="fas fa-plus"></i> Add a dose'.html_safe, new_cocktail_dose_path(@cocktail), class: "btn btn-primary" %>
  <%= link_to '<i class="fas fa-undo-alt"></i> Back'.html_safe, cocktails_path, class: "btn btn-primary" %>
</div>

<!-- <table>
    <thead>
        <tr>
            <th colspan="2">The table header</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>The table body</td>
            <td>with two columns</td>
        </tr>
    </tbody>
</table> -->

app/views/doses/_form.html.erb
<div class="container text-center">
  <div class="form-group">
    <%= simple_form_for @dose, :url => {:action => "create"} do |f| %>
      <%= f.input :description %>
      <% f.association :cocktail %>
      <%= f.association :ingredient %>
      <%= f.submit "Validate", class: "btn btn-primary" %>
      <%= link_to '<i class="fas fa-undo-alt"></i> Back'.html_safe, cocktails_path, class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/doses/new.html.erb
  <%= render 'form'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('test_logo.png') %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right search -->

  <div class="navbar-wagon-search navbar-wagon-right">
    <form action="/" class="form-inline hidden-xs">
        <input type="text" placeholder="Search by name" name="query" class="form-control input">
        <button type="submit" class="form-control btn-search">
          <i class="fa fa-search"></i>
        </button>
      </form>
  </div>

  <!-- Dropdown list appearing on mobile only -->
</div>